In [28]:
import random
import numpy as np
import copy

In [29]:
N_city = random.randint(1,10)
city_size_array = np.random.randint(0,100,N_city)

In [30]:
city_size_array

array([30, 77, 12, 35])

In [34]:
current_city_size = city_size_array.copy()

In [35]:
#current_city_size[0] = 0
print (current_city_size)
print (city_size_array)

[30 77 12 35]
[30 77 12 35]


In [10]:
standard_weight = []
for i in range(N_city):
    standard_weight.append(city_size_array[i]/sum(city_size_array))

In [13]:
standard_weight

[0.1574539363484087,
 0.15912897822445563,
 0.1390284757118928,
 0.02847571189279732,
 0.10887772194304858,
 0.020100502512562814,
 0.1407035175879397,
 0.035175879396984924,
 0.11892797319932999,
 0.09212730318257957]

In [ ]:
def search_city_for_refuge()